baseURL = 'https://santrix.github.io/HC-BETA-001'
languageCode = 'en-us'
paginate = 6
theme= "coHub"
title = 'HASSCORP'
 
  # Main Menu
  [[menu.Main]]
  name = "Exhibición"
  url= "#gallery"
  weight = 1
  [[menu.Main]]
  name = "Servicios"
  url= "#service"
  weight = 2
  [[menu.Main]]
  name = "Sobre Nosotros"
  url= "/about/"
  weight = 3
  [[menu.Main]]
  name = "Noticias"
  url= "#blog"
  weight = 4
 # [[menu.Main]]
 # name = "Precios"
 # url= "#pricing"
 # weight = 5
 # [[menu.Main]]
 # name = "Preguntas"
 # url= "#faq"
 # weight = 6
  [[menu.Main]]
  name = "Contacto"
  url= "/contact/"
  weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2

[params]
  # theme_overrides = "css/overrides.css"
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} <a href=\"https://staticmania.com/\" target=\"_blank\">StaticMania </a>"
  fabFormURL =  "https://fabform.io/f/u00kv3-"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/logo.png"
  footerlogo = "images/logo.png"
  footerDescription = "Hasscorp una empresa de FM"

#  [params.address]
#  address = "115 W 18th St. <br>  New York, NY 10011"
#  email = "hello@example.com"
#  openingDesc = "Give us a call or drop by anytime, we endeavour to answer all enquiries within 24 hours on business days."
#  openingHours = "We are open from 7am — 7pm week days."
#  phone = "+(448) 833 5272 332"

 # [params.map]
 # APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
 # latitude = "45.4502528"
 # longitude = "-122.783407"
 # pinImage = "images/pin.png"

  # Social icons
 # [[params.social]]
 # icon = "ti-facebook"
 # url = "https://www.facebook.com/santisayago"
 # weight = 1
  [[params.social]]
  icon = "ti-email"
  url = "contacto@hasscorp.com"
  weight = 2
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/hasscorp.arg"
  weight = 3