baseURL = 'https://santrix.github.io/HC-BETA-001'
languageCode = 'en-us'
paginate = 6
theme= "coHub"
title = 'HASSCORP'
 
  # Main Menu
  [[menu.Main]]
  name = "Servicios"
  url= "#service"
  weight = 1
  [[menu.Main]]
  name = "Exhibición"
  url= "#gallery"
  weight = 2
 # [[menu.Main]]
 # name = "Noticias"
 # url= "#blog"
 # weight = 3
 # [[menu.Main]]
 # name = "Precios"
 # url= "#pricing"
 # weight = 5
 # [[menu.Main]]
 # name = "Preguntas"
 # url= "#faq"
 # weight = 6
  [[menu.Main]]
  name = "Sobre Nosotros"
  url= "/about/"
  weight = 4
  [[menu.Main]]
  name = "Contacto"
  url= "/contact/"
  weight = 5


  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2

[params]
 # theme_overrides = "css/overrides.css"
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} <a href=\"https://www.linkedin.com/in/santiago-sayago-a553a63a/\" target=\"_blank\">Web Desing</a>"
  fabFormURL =  ""
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/logo.png"
  footerlogo = "images/logo.png"
  footerDescription = "Hasscorp una empresa de FM"

  [params.address]
  address = "Simbrón 5707 <br>  CABA, BsAs, Argentina"
  email = "contacto@hasscorp.com"
  openingDesc = "Puede llamarnos o visitarnos en cualquier momento. Nos comprometemos a responder a todas las consultas en un plazo de 24 horas durante los días laborables."
  openingHours = "Abrimos de 9 a 18"
  phone = "+54 11 3352 6294"

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "-34.61984067729137"
  longitude = "-58.52602237095671"
  pinImage = "images/pin.png"

  # Social icons
  [[params.social]]
  name = "WhatsApp"
  icon = "ti-mobile"
  url = "https://wa.me/541133526294"
  weight = 1
  [[params.social]]
  icon = "ti-email"
  mail = "contacto@hasscorp.com"
  weight = 2
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/hasscorp.arg"
  weight = 3